import forms from '@tailwindcss/forms'
import containerQueries from '@tailwindcss/container-queries'

/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    './app/components/**/*.{js,vue,ts}',
    './app/layouts/**/*.vue',
    './app/pages/**/*.vue',
    './app/plugins/**/*.{js,ts}',
    './app/app.vue',
    './app/error.vue',
  ],
  theme: {
    extend: {
      colors: {
        'surface-dim': '#131313',
        'surface-tint': '#3cddc7',
        'on-tertiary-fixed': '#251a00',
        'surface-container': '#201f1f',
        outline: '#859490',
        'on-primary-fixed': '#00201c',
        'tertiary-fixed-dim': '#f7be1d',
        'tertiary-fixed': '#ffdf9a',
        'surface-container-high': '#2a2a2a',
        error: '#ffb4ab',
        'on-primary-fixed-variant': '#005047',
        'surface-bright': '#393939',
        'inverse-primary': '#006b5f',
        'error-container': '#93000a',
        'inverse-surface': '#e5e2e1',
        'on-primary': '#003731',
        'surface-container-lowest': '#0e0e0e',
        'on-primary-container': '#00574d',
        'on-tertiary-fixed-variant': '#5a4300',
        'on-surface-variant': '#bacac5',
        secondary: '#c8c6c5',
        'on-secondary': '#313030',
        'primary-fixed-dim': '#3cddc7',
        'on-surface': '#e5e2e1',
        'on-secondary-fixed': '#1c1b1b',
        'on-tertiary': '#3f2e00',
        'secondary-fixed-dim': '#c8c6c5',
        'surface-container-highest': '#353534',
        'surface-container-low': '#1c1b1b',
        tertiary: '#ffd574',
        'on-error-container': '#ffdad6',
        'outline-variant': '#3c4a46',
        surface: '#131313',
        background: '#131313',
        'on-tertiary-container': '#624900',
        'surface-variant': '#353534',
        'on-secondary-container': '#b7b5b4',
        'secondary-container': '#474746',
        'primary-container': '#2dd4bf',
        'secondary-fixed': '#e5e2e1',
        'tertiary-container': '#edb60f',
        'on-secondary-fixed-variant': '#474746',
        'primary-fixed': '#62fae3',
        'inverse-on-surface': '#313030',
        primary: '#57f1db',
        'on-error': '#690005',
        'on-background': '#e5e2e1',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Manrope', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        body: ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        label: ['Space Grotesk', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      },
      keyframes: {
        shimmer: {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-20px)' },
        },
      },
      animation: {
        shimmer: 'shimmer 3s infinite linear',
        float: 'float 6s ease-in-out infinite',
        'slow-spin': 'spin 12s linear infinite',
      },
    },
  },
  plugins: [forms, containerQueries],
}
